# Generated by Django 5.1 on 2024-08-25 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_loader_delete_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='event_search',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('category', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('img_src', models.CharField(max_length=255)),
            ],
        ),
    ]
