# Generated by Django 5.1 on 2024-08-25 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_event_search'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event_search',
            name='date',
            field=models.CharField(max_length=255),
        ),
    ]
