# Generated by Django 5.1 on 2024-08-31 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_delete_event_search_loader_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='booking',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('phone', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('comment', models.CharField(default='-', max_length=255)),
            ],
        ),
    ]
