# Generated by Django 5.1 on 2024-09-02 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_booking_email'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='booking',
            new_name='bookings',
        ),
    ]
